mod autocomplete;
pub mod dialogs;
mod editor;
mod focusable_frame;
pub mod help;
mod preview;
pub mod prompt_editor;
mod prompt_export_list;
mod prompt_menu;
mod prompts_menu;
mod sidebar;
mod slots;
mod tab_bar;
mod variable_editor;
mod variable_export_list;
mod variable_list;
mod variable_menu;

pub use editor::EditorPanel;
pub use help::HelpWindow;
pub use preview::PreviewPanel;
pub use sidebar::SidebarPanel;
pub use slots::SlotPanel;
pub use tab_bar::TabBarPanel;
pub use variable_editor::VariableEditorPanel;
