// Re-export WASM module
// The WASM files are generated by `cargo xtask build-wasm`
export * from "./wasm/promptgen_core";
export { default as init } from "./wasm/promptgen_core";

// Re-export TypeScript types
export * from "./types";
